[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oct_labeler"
dependencies = [
  "PySide6",
  "pyqtgraph",
  "numpy",
  "scipy",
  "click",
  "PyInstaller; platform_system=='Windows'",
]
dynamic = ["version"]

[project.scripts]
oct-label = "oct_labeler.cli:cli"

[tools.setuptools.dynamic]
version = {attr = "oct_labeler.__version__"}
